package com.qxml.transform.collect.reset_ttr

object ConstraintLayoutResetAttr {

    val map = hashMapOf<String, String>().apply {
        put("layout_constrainedHeight", "")
        put("layout_constrainedWidth", "")
        put("layout_constraintBaseline_toBaselineOf", "")
        put("layout_constraintBottom_toBottomOf", "")
        put("layout_constraintBottom_toTopOf", "")
        put("layout_constraintCircle", "")
        put("layout_constraintCircleAngle", "")
        put("layout_constraintCircleRadius", "")
        put("layout_constraintDimensionRatio", "")
        put("layout_constraintEnd_toEndOf", "")
        put("layout_constraintEnd_toStartOf", "")
        put("layout_constraintGuide_begin", "")
        put("layout_constraintGuide_end", "")
        put("layout_constraintGuide_percent", "")
        put("layout_constraintHeight_default", "")
        put("layout_constraintHeight_max", "")
        put("layout_constraintHeight_min", "")
        put("layout_constraintHeight_percent", "")
        put("layout_constraintHorizontal_bias", "")
        put("layout_constraintHorizontal_chainStyle", "")
        put("layout_constraintHorizontal_weight", "")
        put("layout_constraintLeft_toLeftOf", "")
        put("layout_constraintLeft_toRightOf", "")
        put("layout_constraintRight_toLeftOf", "")
        put("layout_constraintRight_toRightOf", "")
        put("layout_constraintStart_toEndOf", "")
        put("layout_constraintStart_toStartOf", "")
        put("layout_constraintTop_toBottomOf", "")
        put("layout_constraintTop_toTopOf", "")
        put("layout_constraintVertical_bias", "")
        put("layout_constraintVertical_chainStyle", "")
        put("layout_constraintVertical_weight", "")
        put("layout_constraintWidth_max", "")
        put("layout_constraintWidth_min", "")
        put("layout_constraintWidth_percent", "")
        put("layout_editor_absoluteX", "")
        put("layout_editor_absoluteY", "")
        put("layout_goneMarginBottom", "")
        put("layout_goneMarginEnd", "")
        put("layout_goneMarginLeft", "")
        put("layout_goneMarginRight", "")
        put("layout_goneMarginStart", "")
        put("layout_goneMarginTop", "")
    }

}