package com.qxml.constant

enum class ValueType {
    REFERENCE_ID,
    REFERENCE_INTEGER,
    REFERENCE_DRAWABLE,
    REFERENCE_STRING,
    REFERENCE_FRACTION,
    REFERENCE_DIMEN,
    REFERENCE_COLOR,
    REFERENCE_BOOLEAN,
    REFERENCE_STYLE,
    REFERENCE_LAYOUT,
    REFERENCE_ANIMATOR,
    REFERENCE_ANIM,
    REFERENCE_ARRAY,
    REFERENCE_XML,
    REFERENCE_ATTR,
    ENUM,
    FLAG,
    SOURCE_STRING, //源字符串
    NULL,
}